// the control class represents a instance on the timeline that affects
// the composition, a list of tracks, or a list of generators.
// It can be used to enable or disable various effects.
// Controls have unique names. They are autogenerated when created and can be renamed by the user

import { linearInterpolate } from "utils/interpolation";
import {
  getAttributeValueWithDefault,
  getElementElement,
} from "utils/xmlfunctions";

// Controls do not affect generators that have already stopped running.
export default class Control {
  name: string = "";
  time: number = 0;
  type: EFFECTTYPE = EFFECTTYPE.None;
  list: string[] = []; // list of track or generator names when type is not global
  effect: Effect = new Effect();

  constructor(namePart: number) {
    this.name = "C".concat(namePart.toString());
  }

  copy(): Control {
    const n = new Control(0);
    n.name = this.name;
    n.time = this.time;
    n.type = this.type;
    n.list = [...this.list];
    n.effect = this.effect.copy();
    return n;
  }

  setAttribute(name: string, value: string): boolean {
    switch (name) {
      case "name":
        this.name = value;
        return true;
      case "type":
        this.type = value as EFFECTTYPE;
        switch (this.type) {
          case EFFECTTYPE.Global:
            this.effect = new GlobalEffect();
            return true;
          case EFFECTTYPE.Track:
            this.effect = new TrackEffect();
            return true;
          case EFFECTTYPE.Generator:
            this.effect = new GeneratorEffect();
            return true;
          default:
            return false;
        }
      case "time":
        this.time = parseFloat(value);
        return true;
      case "list":
        this.list = value.split(",");
        return true;

      default:
        return false;
    }
  }

  appendXML(doc: XMLDocument, elem: Element): void {
    try {
      elem.setAttribute("name", this.name);
      elem.setAttribute("type", this.type);
      elem.setAttribute("time", this.time.toString());
      elem.setAttribute("list", this.list.join(","));
      switch (this.type) {
        case EFFECTTYPE.Global:
          (this.effect as GlobalEffect).appendXML(doc, elem);
          break;
        case EFFECTTYPE.Track:
          (this.effect as TrackEffect).appendXML(doc, elem);
          break;
        case EFFECTTYPE.Generator:
          (this.effect as GeneratorEffect).appendXML(doc, elem);
          break;
      }
    } catch (e) {
      throw new Error(`Control appendxml error ${e} `);
    }
  }

  static getXml(elem: Element, version: string): Control {
    try {
      const e: Control = new Control(0);
      e.name = getAttributeValueWithDefault(
        elem,
        "name",
        "string",
        true
      ) as string;
      e.type = getAttributeValueWithDefault(
        elem,
        "type",
        "string",
        true
      ) as EFFECTTYPE;
      e.time = getAttributeValueWithDefault(
        elem,
        "time",
        "float",
        true
      ) as number;
      const list: string = getAttributeValueWithDefault(
        elem,
        "list",
        "string",
        ""
      ) as string;
      if (list != "") e.list = list.split(",");
      else e.list = [];
      switch (e.type) {
        case EFFECTTYPE.Global: {
          const ge: Element | null = getElementElement(elem, "globalEffect");
          if (ge) e.effect = GlobalEffect.getXml(ge, version);
          break;
        }
        case EFFECTTYPE.Track: {
          const te: Element | null = getElementElement(elem, "trackEffect");
          if (te) e.effect = TrackEffect.getXml(te, version);
          break;
        }
        case EFFECTTYPE.Generator: {
          const gene: Element | null = getElementElement(
            elem,
            "generatorEffect"
          );
          if (gene) e.effect = GeneratorEffect.getXml(gene, version);
          break;
        }
      }
      return e;
    } catch (error) {
      throw new Error(`Control getXML error ${error}`);
    }
  }

  static validate(object: Control): string[] {
    const msgs: string[] = [];
    if (object.type == EFFECTTYPE.None)
      msgs.push("Control Effect tyype must be specified.");
    if (
      (object.type == EFFECTTYPE.Track ||
        object.type == EFFECTTYPE.Generator) &&
      (!object.list || object.list.length == 0)
    )
      msgs.push(
        "Track or Generator Effect must have at least one item identified."
      );

    return msgs;
  }
}

// As of this initial writing, the effects that can be affected are
// -    turn the room reverb, compressor, or equalizer on and off
// -    A generator's reverb, tremolo, or vibrato effects.
// -    A generator's sequence played either backwards or reflected about a pitch
// -    Add a list of pitches at specific intervals above or below the pitch
//      of the generator
// Effects occur as soon as they are encountered on the time line. This may
// be in the middle of a generator's creation and affects all of its sources.
export enum EFFECTTYPE {
  "None" = "None",
  "Global" = "Global",
  "Track" = "Track",
  "Generator" = "Generator",
}
export type EffectType = Effect | GlobalEffect | TrackEffect | GeneratorEffect;
export class Effect {
  copy(): Effect {
    const n: Effect = new Effect();
    return n;
  }
}

// effects for room - reverb on/off, compressor on/off, equalizer on/off,
// volume ramp up/down
export class GlobalEffect extends Effect {
  reverbEnable: boolean = true;
  compressorEnable: boolean = true;
  equalizerEnable: boolean = true;
  volumeStart: number = 0; // dB/sec
  volumeStop: number = 0; // dB/sec
  volumeDuration: number = 0; // sec
  #startTime: number = 0;
  #stopTime: number = 0;

  override copy(): GlobalEffect {
    const n = new GlobalEffect();
    n.reverbEnable = this.reverbEnable;
    n.compressorEnable = this.compressorEnable;
    n.equalizerEnable = this.equalizerEnable;
    n.volumeStart = this.volumeStart;
    n.volumeStop = this.volumeStop;
    n.volumeDuration = this.volumeDuration;
    n.#startTime = this.#startTime;
    n.#stopTime = this.#stopTime;
    return n;
  }

  setAttribute(type: string, value: string): boolean {
    switch (type) {
      case "reverbEnable":
        this.reverbEnable = value == "true";
        return true;
      case "compressorEnable":
        this.compressorEnable = value == "true";
        return true;
      case "equalizerEnable":
        this.equalizerEnable = value == "true";
        return true;
      case "volumeStop":
        this.volumeStop = parseFloat(value);
        return true;
      case "volumeStart":
        this.volumeStart = parseFloat(value);
        return true;
      case "volumeDuration":
        this.volumeDuration = parseFloat(value);
        return true;
      default:
        return false;
    }
  }

  initializeVolumeRamp(time: number) {
    this.#startTime = time;
    this.#stopTime = time + this.volumeDuration;
  }

  getCurrentValues(time: number): {
    reverbEnable: boolean;
    compressorEnable: boolean;
    equalizerEnable: boolean;
    volume: number | undefined;
  } {
    let newVolume: number | undefined = undefined;
    if (time >= this.#startTime && time <= this.#stopTime) {
      newVolume = linearInterpolate(
        time,
        this.#startTime,
        this.#stopTime,
        this.volumeStart,
        this.volumeStop
      );
      newVolume = Math.min(10, Math.max(-10, newVolume));
    } else newVolume = undefined;
    return {
      reverbEnable: this.reverbEnable,
      compressorEnable: this.compressorEnable,
      equalizerEnable: this.equalizerEnable,
      volume: newVolume,
    };
  }

  appendXML(doc: XMLDocument, elem: Element): Element {
    try {
      const newElem: Element = elem;
      const effectElem: Element = doc.createElement("globalEffect");
      newElem.appendChild(effectElem);
      effectElem.setAttribute(
        "reverbEnable",
        this.reverbEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "compressorEnable",
        this.compressorEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "equalizerEnable",
        this.equalizerEnable ? "true" : "false"
      );
      effectElem.setAttribute("volumeStart", this.volumeStart.toString());
      effectElem.setAttribute("volumeStop", this.volumeStop.toString());
      effectElem.setAttribute("volumeDuration", this.volumeDuration.toString());
      return newElem;
    } catch (e) {
      throw new Error(`GlobalEffect appendXML error ${e} `);
    }
  }

  static getXml(elem: Element, _version: string): GlobalEffect {
    try {
      const e: GlobalEffect = new GlobalEffect();
      e.reverbEnable = getAttributeValueWithDefault(
        elem,
        "reverbEnable",
        "boolean",
        true
      ) as boolean;
      e.compressorEnable = getAttributeValueWithDefault(
        elem,
        "compressorEnable",
        "boolean",
        true
      ) as boolean;
      e.equalizerEnable = getAttributeValueWithDefault(
        elem,
        "equalizerEnable",
        "boolean",
        true
      ) as boolean;
      e.volumeStart = getAttributeValueWithDefault(
        elem,
        "volumeStart",
        "float",
        0
      ) as number;
      e.volumeStop = getAttributeValueWithDefault(
        elem,
        "volumeStop",
        "float",
        0
      ) as number;
      e.volumeDuration = getAttributeValueWithDefault(
        elem,
        "volumeDuration",
        "float",
        0
      ) as number;
      return e;
    } catch (error) {
      throw new Error(`GlobalEffect getXML error ${error} `);
    }
  }

  static validate(_object: GlobalEffect): string[] {
    return [];
  }
}

// effects for tracks - volume ramp up or down
export class TrackEffect extends Effect {
  volumeStart: number = 0; // dB/sec
  volumeStop: number = 0; // dB/sec
  volumeDuration: number = 0; // sec
  #startTime: number = 0;
  #stopTime: number = 0;

  override copy(): TrackEffect {
    const n = new TrackEffect();
    n.volumeStart = this.volumeStart;
    n.volumeStop = this.volumeStop;
    n.volumeDuration = this.volumeDuration;
    n.#startTime = this.#startTime;
    n.#stopTime = this.#stopTime;
    return n;
  }

  setAttribute(type: string, value: string): boolean {
    switch (type) {
      case "volumeStop":
        this.volumeStop = parseFloat(value);
        return true;
      case "volumeStart":
        this.volumeStart = parseFloat(value);
        return true;
      case "volumeDuration":
        this.volumeDuration = parseFloat(value);
        return true;
      default:
        return false;
    }
  }

  initializeVolumeRamp(time: number) {
    this.#startTime = time;
    this.#stopTime = time + this.volumeDuration;
  }

  getCurrentValues(time: number): { volume: number } {
    let newVolume: number = this.volumeStart;
    newVolume = linearInterpolate(
      time,
      this.#startTime,
      this.#stopTime,
      this.volumeStart,
      this.volumeStop
    );
    newVolume = Math.min(10, Math.max(-10, newVolume));
    return { volume: newVolume };
  }

  appendXML(doc: XMLDocument, elem: Element): Element {
    try {
      const newElem: Element = elem;
      const effectElem: Element = doc.createElement("trackEffect");
      newElem.appendChild(effectElem);
      effectElem.setAttribute("volumeStart", this.volumeStart.toString());
      effectElem.setAttribute("volumeStop", this.volumeStop.toString());
      effectElem.setAttribute("volumeDuration", this.volumeDuration.toString());
      return newElem;
    } catch (e) {
      throw new Error(`TrackEffect appendXML error ${e} `);
    }
  }

  static getXml(elem: Element, _version: string): TrackEffect {
    try {
      const e: TrackEffect = new TrackEffect();
      e.volumeStart = getAttributeValueWithDefault(
        elem,
        "volumeStart",
        "float",
        0
      ) as number;
      e.volumeStop = getAttributeValueWithDefault(
        elem,
        "volumeStop",
        "float",
        0
      ) as number;
      e.volumeDuration = getAttributeValueWithDefault(
        elem,
        "volumeDuration",
        "float",
        0
      ) as number;
      return e;
    } catch (error) {
      throw new Error(`TrackEffect getXML error ${error} `);
    }
  }

  // volume limit cannot be greater than 10 when volume ramp is positive
  // or less that -10 when volume ramp is negative
  static validate(_object: TrackEffect): string[] {
    return [];
  }
}

// effect for generators - reverb on/off, tremelo on/off, vibrato on/off
//      reverse sequence, reflect sequence
//      reverse and reflect sequence only apply to pitch
export class GeneratorEffect extends Effect {
  noiseEnable: boolean = true;
  reverbEnable: boolean = true;
  tremoloEnable: boolean = true;
  vibratoEnable: boolean = true;

  override copy(): GeneratorEffect {
    const n = new GeneratorEffect();
    n.noiseEnable = this.noiseEnable;
    n.reverbEnable = this.reverbEnable;
    n.tremoloEnable = this.tremoloEnable;
    n.vibratoEnable = this.vibratoEnable;
    return n;
  }

  setAttribute(type: string, value: string): boolean {
    switch (type) {
      case "noiseEnable":
        this.noiseEnable = value == "true";
        return true;
      case "reverbEnable":
        this.reverbEnable = value == "true";
        return true;
      case "tremoloEnable":
        this.tremoloEnable = value == "true";
        return true;
      case "vibratoEnable":
        this.vibratoEnable = value == "true";
        return true;
      default:
        return false;
    }
  }

  getCurrentValues(_time: number): {
    noiseEnable: boolean;
    reverbEnable: boolean;
    tremoloEnable: boolean;
    vibratoEnable: boolean;
  } {
    return {
      noiseEnable: this.noiseEnable,
      reverbEnable: this.reverbEnable,
      tremoloEnable: this.tremoloEnable,
      vibratoEnable: this.vibratoEnable,
    };
  }

  appendXML(doc: XMLDocument, elem: Element): Element {
    try {
      const newElem: Element = elem;
      const effectElem: Element = doc.createElement("generatorEffect");
      newElem.appendChild(effectElem);
      effectElem.setAttribute(
        "noiseEnable",
        this.noiseEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "reverbEnable",
        this.reverbEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "tremoloEnable",
        this.tremoloEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "vibratoEnable",
        this.vibratoEnable ? "true" : "false"
      );
      return newElem;
    } catch (e) {
      throw new Error(`GeneratorEffect appendXML error ${e} `);
    }
  }

  static getXml(elem: Element, _version: string): GeneratorEffect {
    try {
      const e: GeneratorEffect = new GeneratorEffect();
      e.noiseEnable = getAttributeValueWithDefault(
        elem,
        "noiseEnable",
        "boolean",
        true
      ) as boolean;
      e.reverbEnable = getAttributeValueWithDefault(
        elem,
        "reverbEnable",
        "boolean",
        true
      ) as boolean;
      e.tremoloEnable = getAttributeValueWithDefault(
        elem,
        "tremoloEnable",
        "boolean",
        true
      ) as boolean;
      e.vibratoEnable = getAttributeValueWithDefault(
        elem,
        "vibratoEnable",
        "boolean",
        true
      ) as boolean;
      return e;
    } catch (error) {
      throw new Error(`GeneratorEffect getXML error ${error} `);
    }
  }

  // volume limit cannot be greater than 10 when volume ramp is positive
  // or less that -10 when volume ramp is negative
  static validate(_object: GeneratorEffect): string[] {
    return [];
  }
}
