// the control class represents a instance on the timeline that affects
// the composition, a list of tracks, or a list of generators.
// It can be used to enable or disable various effects.
// Controls have unique names. They are autogenerated when created and can be renamed by the user

import {
  getAttributeValueWithDefault,
  getElementElement,
} from "utils/xmlfunctions";

// Controls do not affect generators that have already stopped running.
export class Control {
  name: string = "";
  time: number = 0;
  type: EFFECTTYPE = EFFECTTYPE.None;
  list: string[] = []; // list of track or generator names when type is not global
  effect: Effect = new Effect();

  constructor(namePart: number) {
    this.name = "C".concat(namePart.toString());
  }

  copy(): Control {
    const n = new Control(0);
    n.name = this.name;
    n.time = this.time;
    n.type = this.type;
    n.list = [...this.list];
    n.effect = this.effect.copy();
    return n;
  }

  setAttribute(name: string, value: string): boolean {
    switch (name) {
      case "name":
        this.name = value;
        return true;
      case "type":
        this.type = value as EFFECTTYPE;
        switch (this.type) {
          case EFFECTTYPE.Global:
            this.effect = new GlobalEffect();
            return true;
          case EFFECTTYPE.Track:
            this.effect = new TrackEffect();
            return true;
          case EFFECTTYPE.Generator:
            this.effect = new GeneratorEffect();
            return true;
          default:
            return false;
        }
      case "time":
        this.time = parseFloat(value);
        return true;
      case "list":
        this.list = value.split(",");
        return true;

      default:
        return false;
    }
  }

  appendXML(doc: XMLDocument, elem: Element): void {
    try {
      elem.setAttribute("name", this.name);
      elem.setAttribute("type", this.type);
      elem.setAttribute("time", this.time.toString());
      elem.setAttribute("list", this.list.join(','));
      switch (this.type) {
        case EFFECTTYPE.Global:
          (this.effect as GlobalEffect).appendXML(doc, elem);
          break;
        case EFFECTTYPE.Track:
          (this.effect as TrackEffect).appendXML(doc, elem);
          break;
        case EFFECTTYPE.Generator:
          (this.effect as GeneratorEffect).appendXML(doc, elem);
          break;
      }
    } catch (e: any) {
      throw new Error(`Control appendxml error ${e} `);
    }
  }

  static getXml(elem: Element, version: string): Control {
    try {
      const e: Control = new Control(0);
      e.name = getAttributeValueWithDefault(
        elem,
        "name",
        "string",
        true
      ) as string;
      e.type = getAttributeValueWithDefault(
        elem,
        "type",
        "string",
        true
      ) as EFFECTTYPE;
      e.time = getAttributeValueWithDefault(
        elem,
        "time",
        "float",
        true
      ) as number;
      const list: string = getAttributeValueWithDefault(
        elem,
        "list",
        "string",
        ""
      ) as string;
      if (list != "") e.list = list.split(',');
      else e.list = [];
      switch (e.type) {
        case EFFECTTYPE.Global:
          const ge: Element | null = getElementElement(elem, "globalEffect");
          if (ge) e.effect = GlobalEffect.getXml(ge, version);
          break;
        case EFFECTTYPE.Track:
          const te: Element | null = getElementElement(elem, "trackEffect");
          if (te) e.effect = TrackEffect.getXml(te, version);
          break;
        case EFFECTTYPE.Generator:
          const gene: Element | null = getElementElement(
            elem,
            "generatorEffect"
          );
          if (gene) e.effect = GeneratorEffect.getXml(gene, version);
          break;
      }
      return e;
    } catch (error: any) {
      throw new Error(`Control getXML error ${error}`);
    }
  }

  static validate(object: Control): string[] {
    const msgs: string[] = [];
    if (object.type == EFFECTTYPE.None)
      msgs.push("Control Effect tyype must be specified.");
    if (
      (object.type == EFFECTTYPE.Track ||
        object.type == EFFECTTYPE.Generator) &&
      (!object.list || object.list.length == 0)
    )
      msgs.push(
        "Track or Generator Effect must have at least one item identified."
      );

    return msgs;
  }
}

// As of this initial writing, the effects that can be affected are
// -    turn the room reverb, compressor, or equalizer on and off
// -    A generator's reverb, tremolo, or vibrato effects.
// -    A generator's sequence played either backwards or reflected about a pitch
// -    Add a list of pitches at specific intervals above or below the pitch
//      of the generator
// Effects occur as soon as they are encountered on the time line. This may
// be in the middle of a generator's creation and affects all of its sources.
export enum EFFECTTYPE {
  "None" = "None",
  "Global" = "Global",
  "Track" = "Track",
  "Generator" = "Generator",
}
export type EffectType = Effect | GlobalEffect | TrackEffect | GeneratorEffect;
export class Effect {
  copy(): Effect {
    const n: Effect = new Effect();
    return n;
  }
}

// effects for room - reverb on/off, compressor on/off, equalizer on/off,
// volume ramp up/down
export class GlobalEffect extends Effect {
  reverbEnable: boolean = true;
  compressorEnable: boolean = true;
  equalizerEnable: boolean = true;
  volumeRamp: number = 0; // dB/sec
  volumeLimit: number = 0; // dB
  #startTime: number = 0;
  #startVolume: number = 0;

  override copy(): GlobalEffect {
    const n = new GlobalEffect();
    n.reverbEnable = this.reverbEnable;
    n.compressorEnable = this.compressorEnable;
    n.equalizerEnable = this.equalizerEnable;
    n.volumeRamp = this.volumeRamp;
    n.volumeLimit = this.volumeLimit;
    return n;
  }

  setAttribute(type: string, value: string): boolean {
    switch (type) {
      case "reverbEnable":
        this.reverbEnable = value == "true";
        return true;
      case "compressorEnable":
        this.compressorEnable = value == "true";
        return true;
      case "equalizerEnable":
        this.equalizerEnable = value == "true";
        return true;
      case "volumeRamp":
        this.volumeRamp = parseFloat(value);
        return true;
      case "volumeLimit":
        this.volumeLimit = parseFloat(value);
        return true;
      default:
        return false;
    }
  }

  initializeVolumeRamp(time: number, volume: number) {
    this.#startTime = time;
    this.#startVolume = volume;
  }

  getCurrentValues(time: number): {
    reverbEnable: boolean;
    compressorEnable: boolean;
    equalizerEnable: boolean;
    volume: number;
  } {
    let newVolume: number = this.#startVolume;
    if (this.volumeRamp != 0 && time > this.#startTime) {
      newVolume =
        this.#startVolume + this.volumeRamp * (time - this.#startTime);
      if (this.volumeRamp < 0)
        newVolume = Math.max(newVolume, this.volumeLimit, -10);
      else newVolume = Math.min(newVolume, this.volumeLimit, 10);
    }
    return {
      reverbEnable: this.reverbEnable,
      compressorEnable: this.compressorEnable,
      equalizerEnable: this.equalizerEnable,
      volume: newVolume,
    };
  }

  appendXML(doc: XMLDocument, elem: Element): Element {
    try {
      const newElem: Element = elem;
      const effectElem: Element = doc.createElement("globalEffect");
      newElem.appendChild(effectElem);
      effectElem.setAttribute(
        "reverbEnable",
        this.reverbEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "compressorEnable",
        this.compressorEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "equalizerEnable",
        this.equalizerEnable ? "true" : "false"
      );
      effectElem.setAttribute("volumeRamp", this.volumeRamp.toString());
      effectElem.setAttribute("volumeLimit", this.volumeLimit.toString());
      return newElem;
    } catch (e: any) {
      throw new Error(`GlobalEffect appendXML error ${e} `);
    }
  }

  static getXml(elem: Element, _version: string): GlobalEffect {
    try {
      const e: GlobalEffect = new GlobalEffect();
      e.reverbEnable = getAttributeValueWithDefault(
        elem,
        "reverbEnable",
        "boolean",
        true
      ) as boolean;
      e.compressorEnable = getAttributeValueWithDefault(
        elem,
        "compressorEnable",
        "boolean",
        true
      ) as boolean;
      e.equalizerEnable = getAttributeValueWithDefault(
        elem,
        "equalizerEnable",
        "boolean",
        true
      ) as boolean;
      e.volumeRamp = getAttributeValueWithDefault(
        elem,
        "volumeRamp",
        "float",
        true
      ) as number;
      e.volumeLimit = getAttributeValueWithDefault(
        elem,
        "volumeLimit",
        "float",
        true
      ) as number;
      return e;
    } catch (error: any) {
      throw new Error(`GlobalEffect getXML error ${error} `);
    }
  }

  static validate(object: GlobalEffect): string[] {
    if (object.volumeRamp < 0 && object.volumeLimit < -10)
      return [
        "Room Volume limit must be greater than -10 when ramp is negative",
      ];
    if (object.volumeRamp > 0 && object.volumeLimit > 10)
      return ["Room Volume limit must be less than 10 when ramp is positive"];
    return [];
  }
}

// effects for tracks - volume ramp up or down
export class TrackEffect extends Effect {
  volumeRamp: number = 0;
  volumeLimit: number = 0; // the minimum or maximum
  #startTime: number = 0; // time that ramp started
  #startVolume: number = 0; // volume at the ramp started

  override copy(): TrackEffect {
    const n = new TrackEffect();
    n.volumeRamp = this.volumeRamp;
    n.volumeLimit = this.volumeLimit;
    n.#startTime = this.#startTime;
    n.#startVolume = this.#startVolume;
    return n;
  }

  setAttribute(type: string, value: string): boolean {
    switch (type) {
      case "volumeRamp":
        this.volumeRamp = parseFloat(value);
        return true;
      case "volumeLimit":
        this.volumeLimit = parseFloat(value);
        return true;
      default:
        return false;
    }
  }

  initializeRamp(time: number, volume: number) {
    this.#startTime = time;
    this.#startVolume = volume;
  }

  getCurrentValues(time: number): { volume: number } {
    if (time < this.#startTime || this.volumeRamp == 0)
      return { volume: this.#startVolume };
    const deltaT: number = time - this.#startTime;
    const newVolume: number = this.#startVolume + this.volumeRamp * deltaT;
    if (this.volumeRamp > 0)
      return { volume: Math.min(this.volumeLimit, newVolume) };
    else return { volume: Math.max(this.volumeLimit, newVolume) };
  }

  appendXML(doc: XMLDocument, elem: Element): Element {
    try {
      const newElem: Element = elem;
      const effectElem: Element = doc.createElement("trackEffect");
      newElem.appendChild(effectElem);
      effectElem.setAttribute("volumeRamp", this.volumeRamp.toString());
      effectElem.setAttribute("volumeLimit", this.volumeLimit.toString());
      return newElem;
    } catch (e: any) {
      throw new Error(`TrackEffect appendXML error ${e} `);
    }
  }

  static getXml(elem: Element, _version: string): TrackEffect {
    try {
      const e: TrackEffect = new TrackEffect();
      e.volumeRamp = getAttributeValueWithDefault(
        elem,
        "volumeRamp",
        "float",
        true
      ) as number;
      e.volumeLimit = getAttributeValueWithDefault(
        elem,
        "volumeLimit",
        "float",
        true
      ) as number;
      return e;
    } catch (error: any) {
      throw new Error(`TrackEffect getXML error ${error} `);
    }
  }

  // volume limit cannot be greater than 10 when volume ramp is positive
  // or less that -10 when volume ramp is negative
  static validate(object: TrackEffect): string[] {
    if (object.volumeRamp < 0 && object.volumeLimit < -10)
      return [
        "Track Volume limit must be greater than -10 when ramp is negative",
      ];
    if (object.volumeRamp > 0 && object.volumeLimit > 10)
      return ["Track Volume limit must be less than 10 when ramp is positive"];
    return [];
  }
}

// effect for generators - reverb on/off, tremelo on/off, vibrato on/off
//      reverse sequence, reflect sequence
//      reverse and reflect sequence only apply to pitch
export class GeneratorEffect extends Effect {
  noiseEnable: boolean = true;
  reverbEnable: boolean = true;
  tremoloEnable: boolean = true;
  vibratoEnable: boolean = true;
  reverseSequence: boolean = false;
  reflectSequence: boolean = false;
  reflectPitch: number = -1;

  override copy(): GeneratorEffect {
    const n = new GeneratorEffect();
    n.noiseEnable = this.noiseEnable;
    n.reverbEnable = this.reverbEnable;
    n.tremoloEnable = this.tremoloEnable;
    n.vibratoEnable = this.vibratoEnable;
    n.reverseSequence = this.reverseSequence;
    n.reflectSequence = this.reflectSequence;
    n.reflectPitch = this.reflectPitch;
    return n;
  }

  setAttribute(type: string, value: string): boolean {
    switch (type) {
      case "noiseEnable":
        this.noiseEnable = value == "true";
        return true;
      case "reverbEnable":
        this.reverbEnable = value == "true";
        return true;
      case "tremoloEnable":
        this.tremoloEnable = value == "true";
        return true;
      case "vibratoEnable":
        this.vibratoEnable = value == "true";
        return true;
      case "reverseSequence":
        this.reverseSequence = value == "true";
        return true;
      case "reflectSequence":
        this.reflectSequence = value == "true";
        return true;
      case "reflectPitch":
        this.reflectPitch = parseFloat(value);
        return true;
      default:
        return false;
    }
  }

  getCurrentValues(_time: number): {
    noiseEnable: boolean;
    reverbEnable: boolean;
    tremoloEnable: boolean;
    vibratoEnable: boolean;
    reverseSequence: boolean;
    reflectSequence: boolean;
    reflectPitch: number;
  } {
    return {
      noiseEnable: this.noiseEnable,
      reverbEnable: this.reverbEnable,
      tremoloEnable: this.tremoloEnable,
      vibratoEnable: this.vibratoEnable,
      reverseSequence: this.reverseSequence,
      reflectSequence: this.reflectSequence,
      reflectPitch: this.reflectPitch,
    };
  }

  appendXML(doc: XMLDocument, elem: Element): Element {
    try {
      const newElem: Element = elem;
      const effectElem: Element = doc.createElement("generatorEffect");
      newElem.appendChild(effectElem);
      effectElem.setAttribute(
        "noiseEnable",
        this.noiseEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "reverbEnable",
        this.reverbEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "tremoloEnable",
        this.tremoloEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "vibratoEnable",
        this.vibratoEnable ? "true" : "false"
      );
      effectElem.setAttribute(
        "reverseSequence",
        this.reverseSequence ? "true" : "false"
      );
      effectElem.setAttribute(
        "reflectSequence",
        this.reflectSequence ? "true" : "false"
      );
      effectElem.setAttribute("reflectPitch", this.reflectPitch.toString());
      return newElem;
    } catch (e: any) {
      throw new Error(`GeneratorEffect appendXML error ${e} `);
    }
  }

  static getXml(elem: Element, _version: string): GeneratorEffect {
    try {
      const e: GeneratorEffect = new GeneratorEffect();
      e.noiseEnable = getAttributeValueWithDefault(
        elem,
        "noiseEnable",
        "boolean",
        true
      ) as boolean;
      e.reverbEnable = getAttributeValueWithDefault(
        elem,
        "reverbEnable",
        "boolean",
        true
      ) as boolean;
      e.tremoloEnable = getAttributeValueWithDefault(
        elem,
        "tremoloEnable",
        "boolean",
        true
      ) as boolean;
      e.vibratoEnable = getAttributeValueWithDefault(
        elem,
        "vibratoEnable",
        "boolean",
        true
      ) as boolean;
      e.reverseSequence = getAttributeValueWithDefault(
        elem,
        "reverseSequence",
        "boolean",
        true
      ) as boolean;
      e.reflectSequence = getAttributeValueWithDefault(
        elem,
        "reflectSequence",
        "boolean",
        true
      ) as boolean;
      e.reflectPitch = getAttributeValueWithDefault(
        elem,
        "reflectPitch",
        "float",
        true
      ) as number;
      return e;
    } catch (error: any) {
      throw new Error(`GeneratorEffect getXML error ${error} `);
    }
  }

  // volume limit cannot be greater than 10 when volume ramp is positive
  // or less that -10 when volume ramp is negative
  static validate(object: GeneratorEffect): string[] {
    if (object.reflectSequence && object.reflectPitch < 0)
      return [
        "A Reflection Pitch must be specified when reflecting a sequence",
      ];
    return [];
  }
}
