// the control class represents a instance on the timeline that effects
// the composition, a list of tracks, or a list of generators.
// It can be used to enable or disable various controls.
// Controls have unique names. They are autogenerated when created and can be renamed by the user

import { linearInterpolate } from "utils/interpolation";
import { getAttributeValueWithDefault } from "utils/xmlfunctions";
import CMGFile from "./cmgfile";

export default class Control {
  name: string = "";
  time: number = 0;
  type: CONTROLTYPE = CONTROLTYPE.None;

  constructor(namePart: number) {
    this.name = "C".concat(namePart.toString());
  }

  copy(): Control {
    const n = new Control(0);
    n.name = this.name;
    n.time = this.time;
    n.type = this.type;
    return n;
  }

  setAttribute(name: string, value: string): boolean {
    switch (name) {
      case "name":
        this.name = value;
        return true;
      case "type":
        this.type = value as CONTROLTYPE;
        return true;
      case "time":
        this.time = parseFloat(value);
        return true;
      default:
        return false;
    }
  }

  appendXML(_: XMLDocument, elem: Element): void {
    elem.setAttribute("name", this.name);
    elem.setAttribute("type", this.type);
    elem.setAttribute("time", this.time.toString());
  }

  static getXml(elem: Element, _: string): Control {
    const e: Control = new Control(0);
    e.name = getAttributeValueWithDefault(
      elem,
      "name",
      "string",
      true,
    ) as string;
    e.type = getAttributeValueWithDefault(
      elem,
      "type",
      "string",
      true,
    ) as CONTROLTYPE;
    e.time = getAttributeValueWithDefault(
      elem,
      "time",
      "float",
      true,
    ) as number;
    return e;
  }

  static validate(
    values: Control,
    fileContents: CMGFile,
    oldName: string,
  ): string[] {
    const errors: string[] = [];
    if (values.name == "") errors.push("Name must not be blank");
    if (values.name != oldName) {
      const cs: Control[] = fileContents.controls;
      for (let i = 0; i < cs.length; i++) {
        if (cs[i].name == values.name) {
          errors.push("A Control with that name already exists");
        }
      }
    }
    if (values.type == CONTROLTYPE.None)
      errors.push("Control Effect tyype must be specified.");
    return errors;
  }
}

export enum CONTROLTYPE {
  "None" = "None",
  "Global" = "Global",
  "Track" = "Track",
  "Generator" = "Generator",
}
export type ControlType =
  | Control
  | GlobalControl
  | TrackControl
  | GeneratorControl;

// effects for room - reverb on/off, compressor on/off, equalizer on/off,
// volume ramp up/down
export class GlobalControl extends Control {
  values: {
    reverbEnable: boolean;
    compressorEnable: boolean;
    equalizerEnable: boolean;
    volumeStart: number; // dB/sec
    volumeStop: number; // dB/sec
    volumeDuration: number; // sec
  } = {
    reverbEnable: true,
    compressorEnable: true,
    equalizerEnable: true,
    volumeStart: 0,
    volumeStop: 0,
    volumeDuration: 0,
  };
  #startTime: number = 0;
  #stopTime: number = 0;
  constructor(number: number) {
    super(number);
    this.type = CONTROLTYPE.Global;
  }
  override copy(): GlobalControl {
    const n = new GlobalControl(0);
    n.name = this.name;
    n.time = this.time;
    n.type = this.type;
    n.values = { ...this.values };
    n.#startTime = this.#startTime;
    n.#stopTime = this.#stopTime;
    return n;
  }

  override setAttribute(name: string, value: string): boolean {
    if (super.setAttribute(name, value)) return true;
    switch (name) {
      case "reverbEnable":
        this.values.reverbEnable = value == "true";
        return true;
      case "compressorEnable":
        this.values.compressorEnable = value == "true";
        return true;
      case "equalizerEnable":
        this.values.equalizerEnable = value == "true";
        return true;
      case "volumeStop":
        this.values.volumeStop = parseFloat(value);
        return true;
      case "volumeStart":
        this.values.volumeStart = parseFloat(value);
        return true;
      case "volumeDuration":
        this.values.volumeDuration = parseFloat(value);
        return true;
      default:
        return false;
    }
  }

  initializeVolumeRamp(time: number) {
    this.#startTime = time;
    this.#stopTime = time + this.values.volumeDuration;
  }

  getCurrentValues(time: number): {
    reverbEnable: boolean;
    compressorEnable: boolean;
    equalizerEnable: boolean;
    volume: number | undefined;
  } {
    let newVolume: number | undefined = undefined;
    if (time >= this.#startTime && time <= this.#stopTime) {
      newVolume = linearInterpolate(
        time,
        this.#startTime,
        this.#stopTime,
        this.values.volumeStart,
        this.values.volumeStop,
      );
      newVolume = Math.min(10, Math.max(-10, newVolume));
    } else newVolume = undefined;
    return {
      reverbEnable: this.values.reverbEnable,
      compressorEnable: this.values.compressorEnable,
      equalizerEnable: this.values.equalizerEnable,
      volume: newVolume,
    };
  }

  override appendXML(doc: XMLDocument, elem: Element): Element {
    const newElem: Element = elem;
    const controlElem: Element = doc.createElement("globalControl");
    newElem.appendChild(controlElem);
    controlElem.setAttribute(
      "reverbEnable",
      this.values.reverbEnable ? "true" : "false",
    );
    controlElem.setAttribute(
      "compressorEnable",
      this.values.compressorEnable ? "true" : "false",
    );
    controlElem.setAttribute(
      "equalizerEnable",
      this.values.equalizerEnable ? "true" : "false",
    );
    controlElem.setAttribute("volumeStart", this.values.volumeStart.toString());
    controlElem.setAttribute("volumeStop", this.values.volumeStop.toString());
    controlElem.setAttribute(
      "volumeDuration",
      this.values.volumeDuration.toString(),
    );
    return newElem;
  }

  static override getXml(elem: Element, version: string): GlobalControl {
    const control: Control = Control.getXml(elem, version);
    const c: GlobalControl = new GlobalControl(0);
    c.name = control.name;
    c.time = control.time;

    c.values.reverbEnable = getAttributeValueWithDefault(
      elem,
      "reverbEnable",
      "boolean",
      true,
    ) as boolean;
    c.values.compressorEnable = getAttributeValueWithDefault(
      elem,
      "compressorEnable",
      "boolean",
      true,
    ) as boolean;
    c.values.equalizerEnable = getAttributeValueWithDefault(
      elem,
      "equalizerEnable",
      "boolean",
      true,
    ) as boolean;
    c.values.volumeStart = getAttributeValueWithDefault(
      elem,
      "volumeStart",
      "float",
      0,
    ) as number;
    c.values.volumeStop = getAttributeValueWithDefault(
      elem,
      "volumeStop",
      "float",
      0,
    ) as number;
    c.values.volumeDuration = getAttributeValueWithDefault(
      elem,
      "volumeDuration",
      "float",
      0,
    ) as number;
    return c;
  }

  static override validate(
    c: GlobalControl,
    fileContent?: CMGFile,
    oldName?: string,
  ): string[] {
    const e: string[] = [];
    if (fileContent != undefined && oldName != undefined)
      e.concat(Control.validate(c, fileContent, oldName));
    return e;
  }
}

// effects for tracks - volume ramp up or down
export class TrackControl extends Control {
  values: {
    list: string[];
    volumeStart: number; // dB/sec
    volumeStop: number; // dB/sec
    volumeDuration: number; // sec
  } = { list: [], volumeStart: 0, volumeStop: 0, volumeDuration: 0 };
  #startTime: number = 0;
  #stopTime: number = 0;

  override copy(): TrackControl {
    const n = new TrackControl(0);
    n.name = this.name;
    n.time = this.time;
    n.values = { ...this.values };
    n.#startTime = this.#startTime;
    n.#stopTime = this.#stopTime;
    return n;
  }

  override setAttribute(name: string, value: string): boolean {
    if (super.setAttribute(name, value)) return true;
    switch (name) {
      case "list":
        this.values.list = value.split(",");
        return true;
      case "volumeStop":
        this.values.volumeStop = parseFloat(value);
        return true;
      case "volumeStart":
        this.values.volumeStart = parseFloat(value);
        return true;
      case "volumeDuration":
        this.values.volumeDuration = parseFloat(value);
        return true;
      default:
        return false;
    }
  }

  initializeVolumeRamp(time: number) {
    this.#startTime = time;
    this.#stopTime = time + this.values.volumeDuration;
  }

  getCurrentValues(time: number): { volume: number } {
    let newVolume: number = this.values.volumeStart;
    newVolume = linearInterpolate(
      time,
      this.#startTime,
      this.#stopTime,
      this.values.volumeStart,
      this.values.volumeStop,
    );
    newVolume = Math.min(10, Math.max(-10, newVolume));
    return { volume: newVolume };
  }

  override appendXML(doc: XMLDocument, elem: Element): Element {
    const newElem: Element = elem;
    const controlElem: Element = doc.createElement("trackControl");
    newElem.appendChild(controlElem);
    elem.setAttribute("list", this.values.list.join(","));
    controlElem.setAttribute("volumeStart", this.values.volumeStart.toString());
    controlElem.setAttribute("volumeStop", this.values.volumeStop.toString());
    controlElem.setAttribute(
      "volumeDuration",
      this.values.volumeDuration.toString(),
    );
    return newElem;
  }

  static override getXml(elem: Element, version: string): TrackControl {
    const control: Control = Control.getXml(elem, version);
    const c: TrackControl = new TrackControl(0);
    c.name = control.name;
    c.time = control.time;
    const list: string = getAttributeValueWithDefault(
      elem,
      "list",
      "string",
      "",
    ) as string;

    if (list != "") c.values.list = list.split(",");
    else c.values.list = [];

    c.values.volumeStart = getAttributeValueWithDefault(
      elem,
      "volumeStart",
      "float",
      0,
    ) as number;
    c.values.volumeStop = getAttributeValueWithDefault(
      elem,
      "volumeStop",
      "float",
      0,
    ) as number;
    c.values.volumeDuration = getAttributeValueWithDefault(
      elem,
      "volumeDuration",
      "float",
      0,
    ) as number;
    return c;
  }

  static override validate(
    c: TrackControl,
    fileContent?: CMGFile,
    oldName?: string,
  ): string[] {
    const e: string[] = [];
    if (fileContent != undefined && oldName != undefined)
      e.concat(Control.validate(c, fileContent, oldName));
    if (c.values.list.length == 0)
      e.push("Track Control must have at least one item identified.");
    return e;
  }
}

// effect for generators - reverb on/off, tremolo on/off, vibrato on/off
//      reverse sequence, reflect sequence
//      reverse and reflect sequence only apply to pitch
export class GeneratorControl extends Control {
  values: {
    list: string[];
    noiseEnable: boolean;
    reverbEnable: boolean;
    tremoloEnable: boolean;
    vibratoEnable: boolean;
  } = {
    list: [],
    noiseEnable: true,
    reverbEnable: true,
    tremoloEnable: true,
    vibratoEnable: true,
  };

  override copy(): GeneratorControl {
    const n = new GeneratorControl(0);
    n.name = this.name;
    n.time = this.time;
    n.type = this.type;
    n.values = { ...this.values };
    return n;
  }

  override setAttribute(name: string, value: string): boolean {
    if (super.setAttribute(name, value)) return true;

    switch (name) {
      case "list":
        this.values.list = value.split(",");
        return true;
      case "noiseEnable":
        this.values.noiseEnable = value == "true";
        return true;
      case "reverbEnable":
        this.values.reverbEnable = value == "true";
        return true;
      case "tremoloEnable":
        this.values.tremoloEnable = value == "true";
        return true;
      case "vibratoEnable":
        this.values.vibratoEnable = value == "true";
        return true;
      default:
        return false;
    }
  }

  getCurrentValues(_time: number): {
    noiseEnable: boolean;
    reverbEnable: boolean;
    tremoloEnable: boolean;
    vibratoEnable: boolean;
  } {
    return {
      noiseEnable: this.values.noiseEnable,
      reverbEnable: this.values.reverbEnable,
      tremoloEnable: this.values.tremoloEnable,
      vibratoEnable: this.values.vibratoEnable,
    };
  }

  override appendXML(doc: XMLDocument, elem: Element): Element {
    const newElem: Element = elem;
    const controlElem: Element = doc.createElement("generatorControl");
    newElem.appendChild(controlElem);
    elem.setAttribute("list", this.values.list.join(","));
    controlElem.setAttribute(
      "noiseEnable",
      this.values.noiseEnable ? "true" : "false",
    );
    controlElem.setAttribute(
      "reverbEnable",
      this.values.reverbEnable ? "true" : "false",
    );
    controlElem.setAttribute(
      "tremoloEnable",
      this.values.tremoloEnable ? "true" : "false",
    );
    controlElem.setAttribute(
      "vibratoEnable",
      this.values.vibratoEnable ? "true" : "false",
    );
    return newElem;
  }

  static override getXml(elem: Element, version: string): GeneratorControl {
    const control: Control = Control.getXml(elem, version);
    const c: GeneratorControl = new GeneratorControl(0);
    c.name = control.name;
    c.time = control.time;
    const list: string = getAttributeValueWithDefault(
      elem,
      "list",
      "string",
      "",
    ) as string;

    if (list != "") c.values.list = list.split(",");
    else c.values.list = [];

    c.values.noiseEnable = getAttributeValueWithDefault(
      elem,
      "noiseEnable",
      "boolean",
      true,
    ) as boolean;
    c.values.reverbEnable = getAttributeValueWithDefault(
      elem,
      "reverbEnable",
      "boolean",
      true,
    ) as boolean;
    c.values.tremoloEnable = getAttributeValueWithDefault(
      elem,
      "tremoloEnable",
      "boolean",
      true,
    ) as boolean;
    c.values.vibratoEnable = getAttributeValueWithDefault(
      elem,
      "vibratoEnable",
      "boolean",
      true,
    ) as boolean;
    return c;
  }

  static override validate(
    c: GeneratorControl,
    fileContent?: CMGFile,
    oldName?: string,
  ): string[] {
    const e: string[] = [];
    if (fileContent != undefined && oldName != undefined)
      e.concat(Control.validate(c, fileContent, oldName));
    if (c.values.list.length == 0)
      e.push("Generator Control must have at least one item identified.");

    return e;
  }
}
